# my global config
global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds. Default is every 1 minute.
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.

scrape_configs:
  - job_name: "UserManagement"
    static_configs:
      - targets: ["localhost:5015"]